import { z } from "zod";

export const topicValues = [
  "world",
  "politics",
  "business",
  "markets",
  "technology",
  "science",
  "ai",
  "health",
  "climate",
  "culture",
  "sports",
] as const;

export const sourceSchema = z.object({
  id: z.string(),
  name: z.string(),
  homepageUrl: z.string().url(),
  feedUrl: z.string().url(),
  language: z.string().default("en"),
  topics: z.array(z.enum(topicValues)).default([]),
  priority: z.number().int().min(1).max(10).default(5),
});

export const articleSchema = z.object({
  id: z.string(),
  title: z.string(),
  outboundUrl: z.string().url(),
  sourceId: z.string(),
  sourceName: z.string(),
  publishedAt: z.string(),
  discoveredAt: z.string(),
  summary: z.string(),
  whyItMatters: z.string(),
  topics: z.array(z.enum(topicValues)),
  tags: z.array(z.string()),
  entities: z.array(z.string()),
  confidenceScore: z.number().min(0).max(1),
  rankScore: z.number().min(0),
  language: z.string(),
  imageUrl: z.string().url().optional(),
  enrichmentStatus: z.enum(["seeded", "fallback", "enriched"]),
});

export const articleListQuerySchema = z.object({
  limit: z.coerce.number().int().min(1).max(50).default(20),
  cursor: z.string().optional(),
  topic: z.enum(topicValues).optional(),
  source: z.string().optional(),
  search: z.string().trim().min(1).optional(),
  language: z.string().trim().min(1).optional(),
  publishedFrom: z.string().optional(),
  publishedTo: z.string().optional(),
});

export type Topic = (typeof topicValues)[number];
export type Source = z.infer<typeof sourceSchema>;
export type Article = z.infer<typeof articleSchema>;
export type ArticleListQuery = z.infer<typeof articleListQuerySchema>;

export const seedSources: Source[] = sourceSchema.array().parse([
  {
    id: "reuters-world",
    name: "Reuters World News",
    homepageUrl: "https://www.reuters.com/world/",
    feedUrl: "https://feeds.reuters.com/reuters/worldNews",
    language: "en",
    topics: ["world", "politics"],
    priority: 10,
  },
  {
    id: "reuters-business",
    name: "Reuters Business News",
    homepageUrl: "https://www.reuters.com/markets/",
    feedUrl: "https://feeds.reuters.com/reuters/businessNews",
    language: "en",
    topics: ["business", "markets"],
    priority: 10,
  },
  {
    id: "bbc-world",
    name: "BBC World",
    homepageUrl: "https://www.bbc.com/news/world",
    feedUrl: "http://feeds.bbci.co.uk/news/world/rss.xml",
    language: "en",
    topics: ["world"],
    priority: 8,
  },
  {
    id: "ars-technica",
    name: "Ars Technica",
    homepageUrl: "https://arstechnica.com/",
    feedUrl: "https://feeds.arstechnica.com/arstechnica/index",
    language: "en",
    topics: ["technology", "science", "ai"],
    priority: 7,
  },
  {
    id: "espn-top",
    name: "ESPN Top Headlines",
    homepageUrl: "https://www.espn.com/",
    feedUrl: "https://www.espn.com/espn/rss/news",
    language: "en",
    topics: ["sports"],
    priority: 6,
  },
]);

export const seedArticles: Article[] = articleSchema.array().parse([
  {
    id: "article-quantum-export-controls",
    title: "Export controls widen as allied governments tighten advanced compute access",
    outboundUrl: "https://www.reuters.com/world/export-controls-advanced-compute-example",
    sourceId: "reuters-world",
    sourceName: "Reuters World News",
    publishedAt: "2026-04-12T05:00:00.000Z",
    discoveredAt: "2026-04-12T05:11:00.000Z",
    summary: "Governments are coordinating a broader export-control regime aimed at advanced compute and dual-use AI infrastructure.",
    whyItMatters: "Agents tracking AI, supply chains, or geopolitics need to understand how hardware access constraints can cascade into product roadmaps and regional capacity.",
    topics: ["world", "politics", "ai"],
    tags: ["export-controls", "chips", "policy"],
    entities: ["United States", "European Union", "NVIDIA"],
    confidenceScore: 0.93,
    rankScore: 98,
    language: "en",
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475",
    enrichmentStatus: "seeded",
  },
  {
    id: "article-market-openings-energy",
    title: "Energy and shipping stocks rally as Red Sea risk premium resurfaces",
    outboundUrl: "https://www.reuters.com/markets/energy-red-sea-risk-premium-example",
    sourceId: "reuters-business",
    sourceName: "Reuters Business News",
    publishedAt: "2026-04-12T04:20:00.000Z",
    discoveredAt: "2026-04-12T04:26:00.000Z",
    summary: "Insurance, tanker, and energy equities rose after renewed shipping risk pushed traders to reprice freight and oil exposure.",
    whyItMatters: "Agents making market or logistics decisions can use this as an early signal that geopolitical transport risk is spilling into broader commodity pricing.",
    topics: ["business", "markets", "world"],
    tags: ["shipping", "energy", "risk"],
    entities: ["Brent Crude", "Red Sea"],
    confidenceScore: 0.91,
    rankScore: 95,
    language: "en",
    imageUrl: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8",
    enrichmentStatus: "seeded",
  },
  {
    id: "article-lab-safety-rules",
    title: "New lab safety guidance puts frontier model reporting under tighter timelines",
    outboundUrl: "https://arstechnica.com/ai/2026/04/frontier-model-reporting-example/",
    sourceId: "ars-technica",
    sourceName: "Ars Technica",
    publishedAt: "2026-04-12T03:40:00.000Z",
    discoveredAt: "2026-04-12T03:50:00.000Z",
    summary: "Updated frontier AI guidance shortens the window for disclosing safety incidents and evaluation findings.",
    whyItMatters: "This changes the operational burden on labs and vendors building or integrating advanced models, especially around incident response and audit trails.",
    topics: ["technology", "ai", "politics"],
    tags: ["frontier-models", "safety", "reporting"],
    entities: ["OpenAI", "Anthropic", "UK AISI"],
    confidenceScore: 0.9,
    rankScore: 94,
    language: "en",
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995",
    enrichmentStatus: "seeded",
  },
  {
    id: "article-heat-health",
    title: "Heat alerts stretch across multiple regions as hospitals expand surge plans",
    outboundUrl: "https://www.bbc.com/news/world-heat-health-example",
    sourceId: "bbc-world",
    sourceName: "BBC World",
    publishedAt: "2026-04-12T02:30:00.000Z",
    discoveredAt: "2026-04-12T02:42:00.000Z",
    summary: "Hospitals and local governments are expanding surge capacity as an extended heat event impacts multiple population centers.",
    whyItMatters: "Agents supporting health operations, travel, logistics, and emergency preparedness can use this to update regional risk assumptions.",
    topics: ["world", "health", "climate"],
    tags: ["heatwave", "public-health", "preparedness"],
    entities: ["WHO", "Southern Europe"],
    confidenceScore: 0.88,
    rankScore: 89,
    language: "en",
    imageUrl: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21",
    enrichmentStatus: "seeded",
  },
  {
    id: "article-sports-rights-bidding",
    title: "Sports rights bidding intensifies as streamers target shoulder programming",
    outboundUrl: "https://www.espn.com/sports/media-rights-bidding-example",
    sourceId: "espn-top",
    sourceName: "ESPN Top Headlines",
    publishedAt: "2026-04-12T01:50:00.000Z",
    discoveredAt: "2026-04-12T02:05:00.000Z",
    summary: "Streaming platforms are chasing adjacent sports programming to complement marquee live rights packages.",
    whyItMatters: "Agents working on media, consumer subscription strategy, or ad forecasting can treat this as a signal of competition spreading beyond the biggest rights deals.",
    topics: ["sports", "business", "culture"],
    tags: ["streaming", "media-rights", "sports-business"],
    entities: ["ESPN", "YouTube", "Amazon"],
    confidenceScore: 0.84,
    rankScore: 81,
    language: "en",
    imageUrl: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211",
    enrichmentStatus: "seeded",
  },
  {
    id: "article-chip-supply-rebound",
    title: "Advanced packaging capacity expands as chip suppliers chase AI demand rebound",
    outboundUrl: "https://www.reuters.com/markets/chip-supply-rebound-example",
    sourceId: "reuters-business",
    sourceName: "Reuters Business News",
    publishedAt: "2026-04-11T23:10:00.000Z",
    discoveredAt: "2026-04-11T23:17:00.000Z",
    summary: "Suppliers are accelerating advanced packaging expansion to capture AI-related demand across servers and networking hardware.",
    whyItMatters: "Agents monitoring AI infrastructure can use this as a supply-side signal that bottlenecks may shift from GPUs alone to packaging and integration capacity.",
    topics: ["business", "markets", "technology", "ai"],
    tags: ["semiconductors", "supply-chain", "ai-infrastructure"],
    entities: ["TSMC", "CoWoS", "NVIDIA"],
    confidenceScore: 0.94,
    rankScore: 99,
    language: "en",
    imageUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
    enrichmentStatus: "seeded",
  },
]);
